# Generated by Django 3.0 on 2020-02-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0002_auto_20200219_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
