# Generated by Django 3.0 on 2020-02-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0003_distance_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=30),
        ),
    ]
