# Generated by Django 3.0.3 on 2020-02-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0004_auto_20200219_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='dest_lat',
            field=models.DecimalField(decimal_places=20, default=None, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='dest_long',
            field=models.DecimalField(decimal_places=20, default=None, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='destination',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='full_dest_address',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='full_origin_address',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='origin',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='origin_lat',
            field=models.DecimalField(decimal_places=20, default=None, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='origin_long',
            field=models.DecimalField(decimal_places=20, default=None, max_digits=30, null=True),
        ),
    ]
