# Generated by Django 3.0 on 2020-02-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0005_auto_20200221_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='distance',
        ),
        migrations.AddField(
            model_name='distance',
            name='calculated_distance',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='dest_lat',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='dest_long',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='destination',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='full_dest_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='full_origin_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='origin_lat',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='origin_long',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
    ]
