# Generated by Django 3.0 on 2020-02-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0006_auto_20200221_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='origin',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
